### ISSUE TITLE
Dutch Surname prefix

### ISSUE THREAD

**Issue by DarkAllMan** [joshfraser/PHP-Name-Parser#15]
Any plans to implement Dutch notation for surnames
For Instance
Peter de Vries, would be listd under V, not under d
So I would very much like a Name Parser which lists the surname like:
surname: Vries
surname prefix: de
Other examples:
Stijn van der Brekel
surname: Brekel
Surname prefix: van der

**Comment by joshfraser** [comment]
It should only take a minor modification to the code to break that out.  If you look at the code, you'll see the array of compound prefixes ("de", "von", etc).  The mechanics are all there already, you'll just need to do a little massaging to get the data into the format you need.  Feel free to submit a pull request if you end up implementing it.  We should keep the existing lname field for backwards compatibility & other countries, but I'm okay with us adding in two additional fields to support this.
