### ISSUE TITLE
Composer supported?

### ISSUE THREAD

**Issue by jenky** [joshfraser/PHP-Name-Parser#18]
Can you add this package to https://packagist.org so we can install it via `composer`

**Comment by joshfraser** [comment]
Why not.

https://packagist.org/packages/joshfraser/php-name-parser

**Comment by jenky** [comment]
Could u please autoload `parser.php` to `composer.json` so we don't have to manually require the file from `vendor` directory

**Comment by joshfraser** [comment]
Feel free to update it and send me a pull request.
