### ISSUE TITLE
Trying to require through composer

### ISSUE THREAD

**Issue by billystalnaker** [joshfraser/PHP-Name-Parser#28]
I like your package, and I want to continue getting updates as you build. But I can't seem to get it via composer. Any suggestions?

**Comment by joshfraser** [comment]
Did you try this already?

"require": {
"joshfraser/php-name-parser": "master-dev"
}

**Comment by billystalnaker** [comment]
Nope, but I will! Thanks!!

**Comment by billystalnaker** [comment]
I tried that, and it messes with my git repo, tries to create a submodule or something like that... So I'm just using the code for now..
